#!/usr/bin/env perl

use strict;
use warnings;
use lib '/opt/rsapp/lib';
do '/opt/rsapp/lib/Common.pm';


# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('RSApp');
