#!/usr/bin/env perl

use strict;
use warnings;
#use lib '/opt/rsapp/lib';
use lib '/data/Docker-Reddit-Sphinxsearch/docker-containers/app/rsapp/lib';
do '/data/Docker-Reddit-Sphinxsearch/docker-containers/app/rsapp/lib/Common.pm';


# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('RSApp');
